version: '2'
services:
  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./etl-workers
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: ./etl-workers
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A celery_config --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
